export const USER_ACTION_TYPES = {
	SET_USER: 'SET_USER',
	SET_USERS: 'SET_USERS',
	SET_NEXT: 'SET_NEXT',
	SET_SELECTED: 'SET_SELECTED',
}

export const MESSAGES_ACTION_TYPES = {
	MESSAGES_SET: 'MESSAGES_SET',
	MESSAGES_APPENDED: 'MESSAGES_APPENDED',
	MESSAGES_SET_NEXT: 'MESSAGES_SET_NEXT'
}

export const SEARCH_ACTION_TYPES = {
	SET_SEARCH: 'SET_SEARCH'
}

export const CHAT_ACTION_TYPES = {
	SET_CHAT_NAME: 'SET_CHAT_NAME',
	SET_CHAT_INFO: 'SET_CHAT_INFO',
	SET_CHAT_ROOMS: 'SET_CHAT_ROOMS',
	SET_CHAT_NEXT: 'SET_CHAT_NEXT',
	CLEAR_CHAT_INFO: 'CLEAR_CHAT_INFO',
	MESSAGES_SET: 'MESSAGES_SET',
	MESSAGES_APPENDED: 'MESSAGES_APPENDED',
}