export const USER_ACTION_TYPES = {
	SET_USER: 'SET_USER',
	SET_USERS: 'SET_USERS',
	ADD_USERS: 'ADD_USERS',
	SET_NEXT: 'SET_NEXT',
	SET_SELECTED: 'SET_SELECTED',
	TOGGLE_USER: 'TOGGLE_USER',
	DESELECT_USERS: 'DESELECT_USERS'
}

export const MESSAGES_ACTION_TYPES = {
	MESSAGES_SET: 'MESSAGES_SET',
	MESSAGES_APPENDED: 'MESSAGES_APPENDED',
	MESSAGES_PREPENDED: 'MESSAGES_PREPENDED',
	MESSAGES_SET_NEXT: 'MESSAGES_SET_NEXT',
	MESSAGES_SET_CHAT_NAME: 'MESSAGES_SET_CHAT_NAME',	
	MESSAGES_SET_CURRENT_ROOM: 'MESSAGES_SET_CURRENT_ROOM',
	MESSAGES_SET_EDIT_ROOM: 'MESSAGES_SET_EDIT_ROOM',
	MESSAGES_ADD_USER_TO_ROOM: 'MESSAGES_ADD_USER_TO_ROOM',
}

export const SEARCH_ACTION_TYPES = {
	SET_SEARCH: 'SET_SEARCH'
}
