export const USER_ACTION_TYPES = {
	SET_USER: 'SET_USER',
	SET_USERS: 'SET_USERS',
	SET_NEXT: 'SET_NEXT',
	SET_SELECTED: 'SET_SELECTED',
	DESELECT_USERS: 'DESELECT_USERS'
}

export const MESSAGES_ACTION_TYPES = {
	MESSAGES_SET: 'MESSAGES_SET',
	MESSAGES_APPENDED: 'MESSAGES_APPENDED',
	MESSAGES_SET_NEXT: 'MESSAGES_SET_NEXT',
	SET_CHAT_NAME: 'SET_CHAT_NAME',	
}

export const SEARCH_ACTION_TYPES = {
	SET_SEARCH: 'SET_SEARCH'
}
